name: Build

concurrency:
  group: build-eden-${{ github.ref }}-info-windows
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */3 * * *'

jobs:
  check_version:
    runs-on: ubuntu-latest
    name: "Check for new version"
    outputs:
      should_build: ${{ steps.compare.outputs.should_build }}

    strategy:
      matrix:
        target: [Info]
    steps:
      - uses: actions/checkout@v5.0.1
        with:
          persist-credentials: false

      - name: Get the latest release count
        id: get_release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          api_url="https://api.github.com/repos/${{ github.repository }}"
          latest_release_info=$(curl -H "Authorization: token $GH_TOKEN" "$api_url/releases/latest")
          last_release_tag=$(echo "$latest_release_info" | jq -r '.tag_name')
          echo "Last release tag: ${last_release_tag}"
          echo "last_release_tag=${last_release_tag}" >> $GITHUB_OUTPUT
          old_count="${last_release_tag##*-}"
          echo "OLD_COUNT=$old_count" >> "$GITHUB_ENV"

      - name: Generate changelog
        run: |
          chmod +x ./changelog.sh
          ./changelog.sh

      - name: Compare tags
        id: compare
        run: |
          NEW_TAG=$(cat ~/tag)
          # Load the commit count generated by changelog.sh
          NEW_COUNT=$(cat ~/count)
          
          LAST_TAG="${{ steps.get_release.outputs.last_release_tag }}"
          
          OLD_COUNT="${LAST_TAG##*-}"
          
          echo "Last release tag: $LAST_TAG"
          echo "New generated tag: $NEW_TAG"
          echo "Comparing Commit Counts: Old ($OLD_COUNT) vs New ($NEW_COUNT)"
          
          if [[ "$NEW_COUNT" == "$OLD_COUNT" ]]; then
            echo "No new commits. Halting build."
            echo "should_build=false" >> $GITHUB_OUTPUT
          else
            echo "Commit count changed ($OLD_COUNT -> $NEW_COUNT). Proceeding with build."
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload tag file
        if: steps.compare.outputs.should_build == 'true'
        uses: actions/upload-artifact@v5.0.0
        with:
          name: tag
          path: ~/tag

      - name: Upload count file
        if: steps.compare.outputs.should_build == 'true'
        uses: actions/upload-artifact@v5.0.0
        with:
          name: count
          path: ~/count

      - name: Upload changelog file
        if: steps.compare.outputs.should_build == 'true'
        uses: actions/upload-artifact@v5.0.0
        with:
          name: changelog
          path: ~/changelog

      - name: Upload source code
        if: steps.compare.outputs.should_build == 'true'
        uses: actions/upload-artifact@v5.0.0
        with:
          name: source
          path: artifacts

  windows:
    needs: check_version
    if: needs.check_version.outputs.should_build == 'true'
    runs-on: ${{ matrix.runs-on }}
    name: "Windows ${{ matrix.toolchain }} ${{ matrix.optimize }} (${{ matrix.arch }})"
    strategy:
      fail-fast: false
      matrix:
        include:
            - toolchain: msvc
              optimize: normal
              arch: x86_64
              runs-on: windows-latest
            - toolchain: clang
              optimize: normal
              arch: x86_64
              runs-on: windows-latest
    defaults:
      run:
        shell: ${{ matrix.toolchain == 'msys2' && 'msys2 {0}' || 'bash {0}' }}
    env:
      TOOLCHAIN: ${{ matrix.toolchain }}
      ARCH: ${{ matrix.arch }}
      OPTIMIZE: ${{ matrix.optimize }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      CXXFLAGS: "-DNOMINMAX"
    steps:
      - uses: actions/checkout@v5.0.1

      - name: Set up MSVC
        if: ${{ matrix.toolchain != 'msys2' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Install vulkan-sdk
        if: ${{ matrix.toolchain != 'msys2' }}
        shell: powershell
        run: |
          ./install-vulkan-sdk.ps1
          
      - name: Install ccache
        if: ${{ matrix.toolchain != 'msys2' && matrix.optimize == 'normal' }}
        shell: bash
        run: |
          choco install ccache -y --no-progress
          
      - name: Install LLVM
        if: ${{ matrix.toolchain != 'msys2' && matrix.toolchain == 'clang' }}
        shell: powershell
        run: |
          ./install-llvm.ps1
          
      - name: Clone Eden
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden
          cd ./eden
          echo "VERSION=$(git rev-list --count HEAD)" >> "${GITHUB_ENV}"

      - name: Restore ccache
        if: ${{ matrix.optimize == 'normal' }}
        uses: actions/cache/restore@v4
        id: restore-ccache-windows
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ matrix.toolchain }}-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.toolchain }}-${{ matrix.arch }}-

      - name: Compile Eden Windows
        run: |
          chmod +x ./eden-windows.sh
          ./eden-windows.sh

      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.1.0
        with:
          nsis-version: '3.11'
          
      - name: Generate installer
        shell: cmd
        working-directory: ${{ github.workspace }}/installer
        run: |
          set TOOLCHAIN=%TOOLCHAIN%
          if /I "%OPTIMIZE%"=="PGO" set TOOLCHAIN=%TOOLCHAIN%-PGO
          makensis /DPRODUCT_TOOLCHAIN=%TOOLCHAIN% /DPRODUCT_VARIANT=%ARCH% /DPRODUCT_VERSION=%VERSION% eden.nsi
          mkdir artifacts 2>nul
          move /y *.exe artifacts\

      - name: Save ccache
        if: ${{ matrix.optimize == 'normal' && github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-ccache-windows.outputs.cache-primary-key }}

      - name: Upload Eden 7z
        uses: actions/upload-artifact@v5.0.0
        with:
          name: eden-windows-${{ matrix.toolchain }}-${{ matrix.optimize }}-${{ matrix.arch }}-7z
          path: eden/build/artifacts/

      - name: Upload Eden installer
        uses: actions/upload-artifact@v5.0.0
        with:
          name: eden-windows-${{ matrix.toolchain }}-${{ matrix.optimize }}-${{ matrix.arch }}-installer
          path: installer/artifacts/

  release:
    if: github.ref_name == 'main' && needs.check_version.outputs.should_build == 'true'
    name: "release"
    needs: [check_version, windows]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6.0.0
        with:
          pattern: "*"
          merge-multiple: true

      - name: Generate changelog
        run: |
          echo "TAG=$(cat tag)" >> "${GITHUB_ENV}"
          echo "COUNT=$(cat count)" >> "${GITHUB_ENV}"
          echo "BODY<<EOF" >> "${GITHUB_ENV}"
          cat changelog >> "${GITHUB_ENV}"
          echo "EOF" >> "${GITHUB_ENV}"

      - name: Release Eden
        uses: softprops/action-gh-release@v2.4.2
        with:
          name: "Eden Unofficial Nightly Release: ${{ env.COUNT }}"
          tag_name: "${{ env.TAG }}"
          body: "${{ env.BODY }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            *.7z
            *.exe
